version: '3'

services:
  app:
    build: .
    command: ["./node_modules/.bin/gulp", "bws"]
    environment:
      - NODE_ENV=development
      - DEBUG=democracyos*
      - MONGO_URL=mongodb://mongo:27017/myDatabase
      - ADMIN_MAIL=it@democracyos.org
      - ADMIN_PASS=123123
      # Mails del staff. Se debe poner el del Admin! (como mínimo). Para más, separar con comas.
      - STAFF=it@democracyos.org,email@example.com
    links:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./ext/lib:/usr/src/ext/lib
      - ./public:/usr/src/public
    tty: true

  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db
