version: '3'

services:
  mongo:
    container_name: mongodb-der
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db


#version: '3'
#
#services:
#  app:
#    build: .
#    command: ["./node_modules/.bin/gulp", "bws"]
#    environment:
#      - NODE_ENV=development
#      - DEBUG=democracyos*
#      - MONGO_URL=mongodb://mongo:27017/myDatabase
      # Variables admin solo utilizadas para migration inicial
#      - ADMIN_MAIL=it@democracyos.org 
#      - ADMIN_PASS=123123
      # Mails del staff. La del admin no se agrega sola. Para más, separar con comas.
#      - STAFF=it@democracyos.org,email@example.com
#    ports:
#      - 3000:3000
#    volumes:
#      - ./ext/lib:/usr/src/ext/lib
#      - ./public:/usr/src/public
#    tty: true

